### ISSUE TITLE
ReX Patches by YT-Advanced versions list

### ISSUE THREAD

**Issue by abdogm** [ReVanced-Extended-Community/Patches-Documentation#4]
Hi
im not pretty sure if this current compatible list you have is for revanced extended or ReX patches 
if it is ReX patches then could you update the youtube app versions for compatibility because right know (september, 2nd, 2023) the support for versions below 18.33.35 is dropped 
https://github.com/YT-Advanced/ReX-patches#-json-format

**Comment by Spacellary** [comment]
This is only for ReVanced Extended made by Inotia (RVX), not ReX.

Also it seems RVX development is resumed.

Cheers!
