### ISSUE TITLE
Unable to enable chapters in fullscreen video

### ISSUE THREAD

**Issue by kalzEOS** [ReVanced-Extended-Community/Patches-Documentation#7]
I have looked through every single section of the settings more than 4 times and I can't find it. I want to be able to see the little arrow where I click on it while the video is in full screen, and then the chapters show on the side while in full-screen. Could you please tell me where in the settings it is? 
This is what I'm talking about
![image](https://github.com/ReVanced-Extended-Community/Patches-Documentation/assets/49320606/dc5080e1-da85-413c-91a3-aebf5c25d20a)

Thanks

**Comment by KobeW50** [comment]
I believe it is fullscreen panels:

Settings > Revanced Extended > Fullscreen > Hide fullscreen panels, off

**Comment by kalzEOS** [comment]
> I believe it is fullscreen panels:
> 
> Settings > Revanced Extended > Fullscreen > Hide fullscreen panels, off

Thank you so much. It was already off and they still didn't show. I had to clear cache and data on the app for it to work. This should be named something better. "Show/hide chapters in fullscreen" would make a ton more sense. I would have never known if you didn't help. Not sure why it's named fullscreen panels.

**Comment by KobeW50** [comment]
> This should be named something better. "Show/hide chapters in fullscreen" would make a ton more sense. I would have never known if you didn't help. Not sure why it's named fullscreen panels. 

"Fullscreen panels" refer to all things that can appear on the right half of fullscreen, such as live-chat, comments, description, playlist videos, and of course chapters.
